version: '3'

services:
  react-app:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"

  db:
    image: postgres:latest
    # volumes:
    #   - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: attendanceJF
    ports:
      - "5432:5432"


  golang-app:
    container_name: golang-app
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:  
      - "8080:8080"
    volumes:
      - ./server/settings/students_data.xlsx:/app/students_data.xlsx
    environment:
      - DB_HOSTNAME=db
      - DB_USERNAME=postgres
      - DB_PORT=5432
      - DB_NAME=attendancejf
      - DB_PASSWORD=123456
      - STUDENT_DATA_PATH=/app/students_data.xlsx
    # env_file:
    #   - server/.env
    depends_on:
      - db # Đảm bảo rằng dịch vụ PostgreSQL được khởi động trước khi ứng dụng Golang bắt đầu chạy
      
